<!--LUCAS SUPERINA 105914669-->

<footer>
    <div class="container">
        <div class="glass-container-footer">
            <div class="footer">
                <ul> <!-- Footer links -->
                    <li><a href="https://terrible-software-inc.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJpIjoiZTBkZGQ2ODY2MzdlNGFkMWI1ODNiN2JjMDg1ZjNkYzkiLCJwIjoiaiJ9">Jira Project</a></li>
                    <li><a href="https://github.com/LucasSuperina/TSI_Website" target="_blank">GitHub</a></li> <!-- Open New Tab to GitHub repository -->
                    <li><a href="mailto:info@terriblesoftwareinc.com">Email Us</a></li>
                    <li>© 2025 Terrible Software Inc.</li>
                </ul>
            </div>
        </div>
    </div>
</footer>